---
DBInfo:
  admin: FactoryInserter
  baseURL: http://phy-k619lf-a.hep.fsu.edu/Factory/mbDB
  inserter: FactoryInserter
  name: mbdb
  reader: FactoryReadUser
  use_database: true
GUIType: Motherboard
SerialCheckSafe: true
#TestHandler: {name: Local, remoteip: localhost}
#TestHandler: {name: SSH, username: <username>, hostname: "TEST_SERVER_IP_ADDRESS", remoteip: <remoteip>}
TestHandler: {name: Local and ZMQ, localip: "localhost", remoteip: 128.186.110.15, username: <username>, serverpath: <serverpath>, serverscript: <serverscript>}
PhysicalTest: []
# name must be the same as what's in the database, or it won't be uploaded properly
Test: { 
PowerSupply: {
  TestClass: TestPower,
  TestPath: C:\Users\lab619\mb_qc_tests\dc_supply,
  TestScript: power_supply.py,
  desc_long: Read voltage and current back from the board,
  desc_short: Ensure board is powered correctly,
  name: Power Supply,
  method: Local,
  required: 1
  },
setup_lpgbts: {
  TestClass: MBTest_SetupLpgbts,
  TestPath: /home/HGCAL_dev/scintmbdev/hgc-engine-tools/mb_tests,
  TestScript: test_startup.py,
  desc_long: Setup DAQ and TRIG lpGBTs,
  desc_short: Check both lpGBTs are in READY state,
  name: setup_lpgbts,
  method: ZMQ,
  required: 1
  }
}
UsingScanner: true
InspectionTest:
- TestClass: Inspection
  name: Inspection1
  required: 1
  checkboxes: 
    - {text: "Is the board bent?", value: False, requirement: False}
    - {text: "Is the board visibly broken?", value: False, requirement: False}
    - {text: "Are any components missing?", value: False, requirement: False}
    - {text: "Are any components visibly broken?", value: False, requirement: False}
  comments: No Comment
